public with sharing class ApiHandler {
    public static Map<String,Object> startExtract(String contentDocumentId)
    {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String ApiEndPoint = 'https://discoveryframeworkidiscover-dev-ed.my.stmfb.stm.salesforce.com/services/data/v55.0/connect/form-reader/contentDocuments/';
        request.setEndpoint();
        request.setMethod('GET');
        return null;
    }

    public static Map<String,Object> startExtract(String contentDocumentId)
    {
        return null;
    }

    public static Map<String,Object> startExtract(String contentDocumentId)
    {
        return null;
    }
    
}
