public with sharing class ScanDocument {
    public ScanDocument() {

    }
    /*
     *
     * @desc send the docuemnt to enstein ocr to extract text
     * @param {String} contentDocumentId is the id of document uploaded on platform
     * @param {String} sessionId id used as an authentication token while doing rest requests 
     */

     // 
    public  Map<String,Object> scanDocument(String contentDocumentId,String sessionId)
    {
        /**
         * Http http = new Http();
         * HttpRequest req = .....
         * 
         */
        return null;
    }
}
