public with sharing class StaticResources {
    public static String API_URL_1 = 'https://discoveryframeworkidiscover-dev-ed.my.stmfb.stm.salesforce.com/services/data/v55.0/connect/form-reader/contentDocuments/';
    public static String API_URL_2 = '/ocrDocumentScanResults';
    public static String accessToken = '00DRM000000G7ke!AQEAQDU8ljR6m0mAwYlwLEEUUTSCsRaXLP078CN9YOOz04weycOEoHWoW7Wz2xMY.lQuLCqwtvBM_AFDhodEp9lALbsptS3V';
}
